### PR TITLE
Limit user rule port match to tcp/udp

### PR DESCRIPTION
**Pull request by brada4**
Avoid mangling udplite et al not shown in luci-app- nor fw4

Signed-off-by: Andris PE <neandris@gmail.com>

### CODE REVIEW

**Comment by hudra0** [comment]
I'm not sure I understand the motivation here - your implementation adds TCP/UDP as default protocols when no protocol is specified. 

Also, the UI explicitly supports ICMP as a protocol option, so we should maintain compatibility with that.

Could you clarify your intended goal with this change?

**Comment by brada4** [comment]
avoid marking
```
meta l4proto {dccp, udplite} th sport 0
```

**Comment by brada4** [comment]
Has to check if ports are used first.

**Comment by brada4** [comment]
Users can make up their own rules for !tcp-udp-icmpx

**Pull request closed without merging**
